# Generated by Django 5.2.2 on 2025-06-08 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('new', 'Новый'), ('design', 'Проектирование'), ('production', 'Производство'), ('ready', 'Готово'), ('shipped', 'Отгружено')], default='new', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='KPIRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('metric', models.CharField(max_length=64)),
                ('value', models.FloatField()),
            ],
            options={
                'unique_together': {('timestamp', 'metric')},
            },
        ),
    ]
