
-- SQLite schema auto‑generated by Django migrations
-- For illustration purposes
CREATE TABLE "dashboard_orderqueue" (
    "id" integer NOT NULL PRIMARY KEY AUTOINCREMENT,
    "created_at" datetime NOT NULL,
    "client" varchar(128) NOT NULL,
    "description" text NOT NULL,
    "status" varchar(32) NOT NULL
);
CREATE TABLE "dashboard_kpirecord" (
    "id" integer NOT NULL PRIMARY KEY AUTOINCREMENT,
    "timestamp" datetime NOT NULL,
    "metric" varchar(64) NOT NULL,
    "value" real NOT NULL,
    UNIQUE ("timestamp", "metric")
);
